### ISSUE TITLE
作者你好, 请问代码中为什么找不到GAT? 

### ISSUE THREAD

**Issue by thisAnyaLee** [limengran98/HGTN#2]
报错如下;

Traceback (most recent call last):
  File "D:\Learn\PycharmProjects\Meta-path\HGTN\main.py", line 354, in <module>
    model = HGTN(type_hyperedge=A.shape[-1],
  File "D:\Learn\PycharmProjects\Meta-path\HGTN\HGTN.py", line 59, in __init__
    self.gat = GAT(self.w_in,self.nhid,self.num_class,self.drpoput ,self.alpha ,self.nheads)
NameError: name 'GAT' is not defined

**Comment by limengran98** [comment]
Hello, you can delete this line. The source code has been fixed.
